package org.mskcc.domain;

public enum ProtocolType {
    TRU_SEQ_RNA_SM_RNA_PROTOCOL_4,
    TRU_SEQ_RIBO_DEPLETE_PROTOCOL_1,
    TRU_SEQ_RNA_FUSION_PROTOCOL_1,
    SMAR_TER_AMPLIFICATION_PROTOCOL_1,
    KAPA_MRNA_STRANDED_SEQ_PROTOCOL_1,
    TRU_SEQ_STRANDING
}
